; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1

framework = arduino

board_build.mcu = esp32s3
board_build.arduino.memory_type = dio_opi
board_build.flash_size = 8MB ; new
board_build.partitions = default_8MB.csv ; new
board_build.flash_mode = qio ; new

build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

lib_ldf_mode = deep+
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_port = COM4
monitor_speed = 115200
upload_port = COM4
upload_speed = 115200